name: pull-request-checks
on:  
  pull_request:
    branches: [ $default-branch ]
jobs:
  compile:
    name: Compiling Source
    runs-on: windows-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Change directory
        run: cd ispw

      - name: Install dependencies
        run: npm ci

      - name: Run compile
        run: npm run compile
